export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_AUTH_STATUS = "SET_AUTH_STATUS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const EDIT_DETAILS = "EDIT_DETAILS";
export const USER_DETAILS_FETCHED = "GET_USER_DETAILS";

export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_ALERT = "HIDE_ALERT";
export const SHOW_ALERT = "SHOW_ALERT";

export const REDIRECT_TO_LOGIN = "REDIRECT_TO_LOGIN";
export const REDIRECT_TO_HOME = "REDIRECT_TO_HOME";
export const REDIRECT_TO_DASHBOARD = "REDIRECT_TO_DASHBOARD";

export const SET_ACTIVE_LINK = "SET_ACTIVE_LINK";

export const DUE_TO_PAY_FETCHED = "DUE_TO_PAY_FETCHED";
export const DUE_STATUS_FETCHED = "HAS_PAID_DUE";

export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const GET_DASHBOARD_OVERVIEW = "DASHBOARD_OVERVIEW";
export const GET_INDUSTRY_TYPE = "GET_INDUSTRY_TYPE";
export const GET_MEMBERSHIP_TYPE = "GET_MEMBERSHIP_TYPE";
export const GET_INDUSTRY_CLASSIFICATION = "GET_INDUSTRY_CLASSIFICATION";
export const LOGOUT = "LOGOUT";

export const DEFAULT_PASSWORD_CHANGED_SUCCESS =
  "DEFAULT_PASSWORD_CHANGED_SUCCESS";
export const CLEAR_PASSWORD = "CLEAR_PASSWORD";
export const PASSWORD_CHANGE = "PASSWORD_CHANGE";

export const LOADER_OFF = "LOADER_OFF";
export const POP_LOADER = "POP_LOADER";
export const PAGE_ERROR = "PAGE_ERROR";
export const PAGE_LOADER = "PAGE_LOADER";
export const POPUP = "POPUP";
export const POPIN = "POPIN";

export const FETCHED_AN_EVENT = "FETCHED_AN_EVENT";
export const GOT_ACTIVE_EVENTS = "GOT_ACTIVE_EVENTS";
export const GOT_CLOSED_EVENTS = "GOT_CLOSED_EVENTS";
export const GOT_ALL_EVENTS = "GOT_ALL_EVENTS";
export const CREATE_EVENT = "CREATE_EVENT";
export const EDIT_EVENT = "EDIT_EVENT";
export const SELECT_EVENT = "SELECT_EVENT";

export const GET_SENT_INVITATION = "GET_SENT_INVITATION";
export const GET_INCOMING_INVITE = "GET_INCOMING_INVITE";
export const SEND_INVITATION = "SEND_INVITATION";
export const INVITE_LOADING = "INVITE_LOADING";
export const INVITE_ERROR = "INVITE_ERROR";

export const GOT_INVITATIONS = "GOT_INVITATIONS";
export const SELECT_INVITAION = "SELECT_INVITAION";
export const I_LOAD = "I_LOAD";
export const I_ERROR = "I_ERROR";

export const SEND_QUESTION = "SEND_QUESTION";
export const SENDING_QUESTION = "SENDING_QUESTION";
export const QUESTION_SENT = "QUESTION_SENT";
export const GET_QUESTIONS = "GET_QUESTIONS";
export const GET_A_QUESTION = "GET_A_QUESTION";
export const EDIT_QUESTION = "EDIT_QUESTION";
export const QUE_ERROR = "QUE_ERROR";

export const PAID = "PAID";
export const FAILED = "FAILED";
export const GOT_PAIDMENT_NEEDS = "GOT_PAIDMENT_NEEDS";
export const LIST_FAILED = "LIST_FAILED";
export const PAY = "PAY";
export const PAY_REF = "PAY_REF";
export const CLEARO = "CLEARO";


export const LOADING_PAYMENTS = "LOADING_PAYMENTS"
export const PAYMENT_FAILED = "PAYMENT_FAILED"
export const GOT_PAID_DETAILS = "GOT_PAID_DETAILS"


export const GET_PAYMENT_HISTORY_REQUEST = "GET_PAYMENT_HISTORY_REQUEST";
export const GET_PAYMENT_HISTORY_REQUEST_SUCCESS =
  "GET_PAYMENT_HISTORY_REQUEST_SUCCESS";
export const GET_PAYMENT_HISTORY_REQUEST_FAILED =
  "GET_PAYMENT_HISTORY_REQUEST_FAILED";


export const REG_DONE = "REG_DONE"
export const BEGIN_REG = "BEGIN_REG"
export const END_REG = "END_REG"


export const SENDING_ARCHIEVE = "SENDING_ARCHIEVE"
export const ARCHIEVE_SENT = "ARCHIEVE_SENT"
export const GET_ARCHIEVES = "GET_ARCHIEVES"
export const GET_A_ARCHIEVE = "GET_A_ARCHIEVE"
export const ARC_ERROR = "ARC_ERROR"


export const CLOSE_ERROR = "CLOSE_ERROR"
export const CLOSE_PASS = "CLOSE_PASS"
export const CLOSE_LOADER = "CLOSE_LOADER"
export const EVENT_CLOSED = "EVENT_CLOSED"

export const DEL_DONE = "DEL_DONE"
export const DEL_FAIL = "DEL_FAIL"
export const DEL_LOAD = "DEL_LOAD"
export const DEL_BACK = "DEL_BACK"
